# -*- coding: utf-8 -*-
"""score_cluster_players.py

Utility script to compute a match score based on how well the selected
players of two national teams align with user‑chosen favourite clusters
for each of the six macro‑positions used in the World‑Cup analysis.

The script:
  • Connects to the SQLite database ``convocados.db`` and extracts the
    player names belonging to each country mentioned in a match string.
  • Loads the distance‑to‑centroid JSON files that were generated by the
    ``assign_players_to_centroids.py`` script (one file per macro‑position).
  • For every position, it looks up the distance of each player to the
    *favourite* cluster supplied by the user and converts it into a
    contribution ``1 / distance`` (players without a recorded distance
    contribute ``0``).
  • Sums the contributions of both teams across all positions and returns
    the total score together with a breakdown per position.

The implementation is deliberately lightweight – it can be called many
times (e.g. to evaluate a whole tournament) without re‑loading JSON files
more than necessary.
"""

import json
import os
import sqlite3
from pathlib import Path
from typing import Dict, List, Tuple, Any, Union
# Reuse normalization logic from player_similarity for consistent name handling
try:
    from data.player_similarity.player_similarity import normalize_string as normalize_name
except ImportError:
    # Fallback: define a local normalization function similar to player_similarity.normalize_string
    import unicodedata
    import re
    def normalize_name(s: str) -> str:
        """Normalize a player name: lowercase, strip accents, collapse whitespace."""
        if not isinstance(s, str):
            return ""
        s = unicodedata.normalize('NFD', s)
        s = s.encode('ascii', 'ignore').decode('utf-8')
        s = s.lower().strip()
        s = re.sub(r"\s+", " ", s)
        return s

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
# Relative paths – adjust only if the project layout changes.

BASE_DIR = Path(__file__).resolve().parent.parent.parent  # project root
DB_PATH = BASE_DIR / "data" / "recommender_data" / "convocados.db"

# ---------------------------------------------------------------------------
# Public helper for programmatic use
# ---------------------------------------------------------------------------

import math

def run_score(match: Union[str, Tuple[str, str]], favourite_clusters: Dict[str, int], db_path: str = None, a: float = 3.0) -> Tuple[float, Dict[str, List[Dict[str, Any]]]]:
    """Convenient wrapper to call :func:`score_match` directly.

    Parameters
    ----------
    match: str or tuple
        Match description, e.g. ``"Argentina vs Francia"`` or ``("Argentina", "Francia")``.
    favourite_clusters: dict
        Mapping ``position → cluster_id``.
    db_path: str, optional
        Path to the ``convocados.db`` SQLite file. If omitted the default path
        ``DB_PATH`` (project ``data/convocados.db``) is used.
    a: float, default 4.0
        Hyperparameter 'a' for the scoring formula.
    """
    path = Path(db_path) if db_path else DB_PATH
    return score_match(favourite_clusters, match, db_path=path, a=a)

DIST_DIR = BASE_DIR / "data" / "clustering_maps"

# Macro‑position names used throughout the project.
POSITIONS = [
    "Goalkeeper",
    "Centerbacks",
    "Fullbacks",
    "Midfielder",
    "Striker",
    "Wingers",
]

# Mapping from macro‑position to the suffix used in the JSON filenames.
# The suffix matches the filenames produced by ``assign_players_to_centroids``.
JSON_SUFFIX = {
    "Goalkeeper": "goalkeeper",
    "Centerbacks": "centerbacks",
    "Fullbacks": "fullbacks",
    "Midfielder": "midfielder",
    "Striker": "striker",
    "Wingers": "wingers",
}

# Cache for loaded JSON data – avoids re‑reading the same file during a
# single script execution.
_distance_cache: Dict[str, Any] = {}

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def load_distance_json(position: str) -> List[Dict[str, Any]]:
    """Load the full‑distances JSON for *position*.

    Parameters
    ----------
    position: str
        One of the macro‑position strings defined in ``POSITIONS``.

    Returns
    -------
    List[Dict]
        The JSON structure – a list of clusters, each containing a
        ``cluster_id`` and a ``players`` list.
    """
    suffix = JSON_SUFFIX[position]
    json_path = DIST_DIR / f"kmeans_{suffix}_full_distances.json"
    if position in _distance_cache:
        return _distance_cache[position]
    with open(json_path, "r", encoding="utf-8") as fp:
        data = json.load(fp)
    _distance_cache[position] = data
    return data


def get_favourite_cluster_distances(
    distance_json: List[Dict[str, Any]], favourite_cluster_id: int
) -> Dict[str, float]:
    """Return a mapping *normalized player name → distance* for the favourite cluster.

    The JSON may contain full names (e.g., "Kylian Mbappé Lottin").
    To allow matching with the shorter names stored in the DB (e.g., "Kylian Mbappé"),
    we store both the original and a normalized version of each name.
    """
    for cluster in distance_json:
        if cluster.get("cluster_id") == favourite_cluster_id:
            lookup: Dict[str, float] = {}
            for p in cluster.get("players", []):
                long_name = p["long_name"]
                distance = p["distance"]
                # Direct mapping by exact name (kept for completeness)
                lookup[long_name] = distance
                # Normalized full name mapping
                norm_full = normalize_name(long_name)
                if norm_full not in lookup:
                    lookup[norm_full] = distance
                # Normalized short name (first two words) mapping to handle abbreviated DB entries
                short_name = " ".join(long_name.split()[:2])
                norm_short = normalize_name(short_name)
                if norm_short not in lookup:
                    lookup[norm_short] = distance
            return lookup
    return {}


def fetch_players_by_country(conn: sqlite3.Connection, country: str) -> List[str]:
    """Return a list with the names of all players from *country*.

    The ``convocados`` table stores the country under the column ``pais`` and
    the player name under ``jugador`` (both strings). If the schema ever
    changes, adapt the column names accordingly.
    """
    cur = conn.cursor()
    cur.execute("SELECT jugador FROM convocados WHERE pais = ?", (country,))
    rows = cur.fetchall()
    # ``rows`` is a list of one‑element tuples.
    return [row[0] for row in rows]


def parse_match_string(match: str) -> Tuple[str, str]:
    """Parse a match string of the form ``"Country1 vs Country2"``.

    The function is tolerant to surrounding whitespace and case.
    """
    parts = match.split("vs")
    if len(parts) != 2:
        raise ValueError(
            f"Invalid match format: '{match}'. Expected 'Country1 vs Country2'."
        )
    return parts[0].strip(), parts[1].strip()

# ---------------------------------------------------------------------------
# Core scoring logic
# ---------------------------------------------------------------------------

def score_match(
    favourite_clusters: Dict[str, int],
    match: Union[str, Tuple[str, str]],
    db_path: Path = DB_PATH,
    a: float = 4.0
) -> Tuple[float, Dict[str, List[Dict[str, Any]]]]:
    """Calculate the total score for a match.

    Parameters
    ----------
    favourite_clusters: dict
        Mapping ``position → cluster_id`` for the *user's* favourite clusters.
    match: str or tuple
        Either a string ``"Country1 vs Country2"`` or a tuple/list ``("Country1", "Country2")``.
    db_path: pathlib.Path, optional
        Path to ``convocados.db``. Defaults to the project‑relative path.
    a: float, default 4.0
        Hyperparameter 'a' for the scoring formula.

    Returns
    -------
    total_score: float
        Sum of the contributions of all players from both teams.
    breakdown: dict
        ``position → list`` where each list element is a dict with keys
        ``player``, ``country`` and ``contribution``.
    """
    # Determine countries from match argument
    if isinstance(match, (list, tuple)):
        if len(match) != 2:
            raise ValueError("match tuple must contain exactly two country names")
        country1, country2 = match[0].strip(), match[1].strip()
    else:
        country1, country2 = parse_match_string(match)

    # Ensure the database file exists before attempting to connect.
    if not Path(db_path).exists():
        # If running in example mode (no real DB), skip DB lookup and use empty player lists.
        # This allows the script to run without a database while still demonstrating scoring logic.
        players_country1, players_country2 = [], []
    else:
        conn = sqlite3.connect(str(db_path))
        try:
            players_country1 = fetch_players_by_country(conn, country1)
            players_country2 = fetch_players_by_country(conn, country2)
        finally:
            conn.close()


    total_score = 0.0
    breakdown: Dict[str, List[Dict[str, Any]]] = {pos: [] for pos in POSITIONS}

    for position in POSITIONS:
        fav_cluster_id = favourite_clusters.get(position)
        if not fav_cluster_id:
            # No favourite cluster defined for this position – skip it.
            continue

        # Load distance data for the position (cached after the first call).
        distance_json = load_distance_json(position)
        fav_distances = get_favourite_cluster_distances(distance_json, fav_cluster_id)

        # Helper to compute contributions for a list of player names.
        def process_players(player_names: List[str], country: str) -> None:
            nonlocal total_score
            for name in player_names:
                # Normalize the DB name before lookup to match the keys created above
                norm_name = normalize_name(name)
                distance = fav_distances.get(name) or fav_distances.get(norm_name)
                if distance is None:
                    contribution = 0.0
                else:
                    if abs(a) < 1e-9:
                        contribution = 1.0 - distance
                    else:
                        exp_neg_a = math.exp(-a)
                        contribution = (math.exp(-a * distance) - exp_neg_a) / (1.0 - exp_neg_a)
                    # Clamp contribution to [0, 1]
                    contribution = max(0.0, min(1.0, contribution))
                if contribution > 0:
                    total_score += contribution
                    breakdown[position].append(
                        {
                            "player": name,
                            "country": country,
                            "contribution": contribution,
                        }
                    )

        process_players(players_country1, country1)
        process_players(players_country2, country2)

    return total_score, breakdown

# ---------------------------------------------------------------------------
# CLI entry point (optional, useful for quick manual testing)
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import argparse
    import json

    parser = argparse.ArgumentParser(
        description="Score a World‑Cup match based on favourite player clusters."
    )
    parser.add_argument(
        "match",
        nargs="?",
        help="Match string in the form 'Country1 vs Country2'",
    )
    parser.add_argument(
        "clusters",
        nargs="?",
        help=(
            "JSON string or path to a JSON file mapping positions to favourite "
            "cluster ids, e.g. '{\"Goalkeeper\": 2, \"Centerbacks\": 1, ...}'"
        ),
    )
    parser.add_argument(
        "--a",
        type=float,
        default=4.0,
        help="Hyperparameter 'a' for the scoring formula (default: 4.0).",
    )
    parser.add_argument(
        "--example",
        action="store_true",
        help="Run a built‑in example with dummy data.",
    )
    args = parser.parse_args()

    if args.example:
        example_match = "Argentina vs Francia"
        # Simple example: favourite cluster 1 for every position.
        example_clusters = {pos: 1 for pos in POSITIONS}
        fav_clusters = example_clusters
        match_str = example_match
    else:
        if not args.match or not args.clusters:
            raise SystemExit("Both <match> and <clusters> arguments are required unless --example is used.")
        # Load the favourite‑cluster mapping – accept a file path or raw JSON.
        try:
            fav_path = Path(args.clusters)
            if fav_path.is_file():
                with open(fav_path, "r", encoding="utf-8") as fp:
                    fav_clusters = json.load(fp)
            else:
                fav_clusters = json.loads(args.clusters)
        except Exception as exc:
            raise SystemExit(f"Unable to read favourite clusters: {exc}")
        match_str = args.match

    total, details = score_match(fav_clusters, match_str, a=args.a)
    print(f"Total match score: {total:.4f}\n")
    for pos, players in details.items():
        if not players:
            continue
        print(f"{pos} (cluster {fav_clusters.get(pos)}):")
        for rec in players:
            print(
                f"  {rec['player']} ({rec['country']}): {rec['contribution']:.4f}"
            )
        print()
