name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: ["main"]

# Otorga permisos para que Actions pueda modificar Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      
      - name: Configurar Pages
        uses: actions/configure-pages@v4
      
      - name: Subir artefacto (Apunta a la carpeta frontend)
        uses: actions/upload-pages-artifact@v3
        with:
          path: './frontend'           
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4